crawler:
  userAgent: "LOSH Bot (github.com/aisbergg/losh)"

log:
  level: info  # debug, info, warning, error, critical
  format: json  # can be either json or console

  fileName: ""
  # https://doc.traefik.io/traefik/observability/logs/#log-rotation
  rotate: true
  maxSize: 5 # in MB
  maxAge: 0  # in days
  maxBackups: 0
  compress: true
  localTime: true
  permissions: "0644"

database:
  host: localhost
  port: 8080
  timeout: 60s
  tls:
    enabled: false
    verify: false
    cert: ""
    key: ""
    caCertificates: []
