model:
  filename: ./wfclient/models.go
client:
  filename: ./wfclient/client.go
models:
  Int:
    model: github.com/99designs/gqlgen/graphql.Int64
  DateTime:
    model: github.com/99designs/gqlgen/graphql.Time
endpoint:
  url: https://wikifactory.com/api/graphql
query:
  - .query.graphql
generate:
  clientV2: true
  clientInterfaceName: "WikifactoryGraphQLClient"
