debug: true # TODO: make configurable


use-iconfont: true

title: LOSH
# base: 127.0.0.1:8080  # used in footer
copy-right: Library of Open Source Hardware # used in footer
description: Library of Open Source Hardware
issue-url: XXX

layout-dark: false

tabler-css-plugins: []

collections:
  docs:
    output: true

defaults:
  - scope:
      type: "pages"
      path: "*.md"
    values:
      layout: markdown
  - scope:
      type: "pages"
    values:
      layout: default
  - scope:
      type: "docs"
    values:
      layout: docs

colors:
  blue:
    class: blue
    hex: "#206bc4"
    title: Blue
  azure:
    class: azure
    hex: "#45aaf2"
    title: Azure
  indigo:
    class: indigo
    hex: "#6574cd"
    title: Indigo
  purple:
    class: purple
    hex: "#a55eea"
    title: Purple
  pink:
    class: pink
    hex: "#f66d9b"
    title: Pink
  red:
    class: red
    hex: "#fa4654"
    title: Red
  orange:
    class: orange
    hex: "#fd9644"
    title: Orange
  yellow:
    class: yellow
    hex: "#f1c40f"
    title: Yellow
  lime:
    class: lime
    hex: "#7bd235"
    title: Lime
  green:
    class: green
    hex: "#5eba00"
    title: Green
  teal:
    class: teal
    hex: "#2bcbba"
    title: Teal
  cyan:
    class: cyan
    hex: "#17a2b8"
    title: Cyan


variants:
  - name: success
    icon: check
  - name: info
    icon: info-circle
  - name: warning
    icon: alert-triangle
  - name: danger
    icon: alert-circle

theme-colors:
  primary:
    class: primary
    title: Primary
  secondary:
    class: secondary
    title: Secondary
  success:
    class: success
    title: Success
  warning:
    class: warning
    title: Warning
  danger:
    class: danger
    title: Danger
  info:
    class: info
    title: Info
  light:
    class: light
    title: Light
  dark:
    class: dark
    title: Dark

button-states:
  - class:
    title: Normal
  - class: active
    title: Active state
  - class: disabled
    title: Disabled

data:
  menu:
    search:
      url: "search"
      icon: search
      title: Search

    explore:
      url: "explore"
      icon: compass
      title: Explore

    about:
      icon: info-circle
      title: About
      children:
        project:
          url: "about/project"
          title: The Project
        faq:
          url: "about/faq"
          title: FAQ
          icon: question-mark


months-short: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
months-long: ["January", "Febuary", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
