# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

root = "."
tmp_dir = "tmp"

[build]
cmd = "yarn run dev && go build -trimpath -o ./build/losh-web ./main.go"
full_bin = "./build/losh-web run -c ./config-dev.yml"
include_ext = ["go", "tpl", "tmpl", "html", "js", "scss", "svg", "jpg", "png"]
exclude_dir = ["tmp", "vendor", "node_modules", "public", "intf/http/assets/tpl", "build"]
log = "air.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = true
kill_delay = 500 # ms

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
