debug:
  enabled: true
  pprof: false
  expvar: false


log:
  level: info  # debug, info, warning, error, critical
  format: json  # can be either json or console


  fileName: ""
  # https://doc.traefik.io/traefik/observability/logs/#log-rotation
  rotate: true
  maxSize: 5 # in MB
  maxAge: 0  # in days
  maxBackups: 0
  compress: true
  localTime: true
  permissions: "0644"


accessLog:
  enabled: true
  # TODO: implement
  fields:
    - remote_IP_address
    - request_method
    - request_path
    - request_protocol
    - server_HTTP_status
    - request_referrer
    - request_user_agent
    - request_duration_in_ms

  # https://doc.traefik.io/traefik/observability/access-logs/#filtering
  filters: ???

  # same as log


server:
  baseURL: ""
  interface: 127.0.0.1
  port: 3000
  trustedDomains:
    - abc.de

  trustedProxies:
    - 172.10.10.10

  # disabled:         -1
  # default:          0
  # best speed:        1
  # best compression:  2
  compress: -1

  cache:
    enabled: false
    expiration: "1m"
    cacheControl: true



  # TODO: ???


  limit:
    enabled: false
    max: 5
    duration: "1m"

  faviconDir: favicon


  tls:
    enabled: false
    certificate: ""
    key: ""
    # https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28recommended.29
    minVersion: VersionTLS12
    cipherSuites:
      # TLS 1.3 Cipher Suites
      - TLS_AES_256_GCM_SHA384
      - TLS_AES_128_GCM_SHA256
      - TLS_CHACHA20_POLY1305_SHA256
      # TLS 1.2 Cipher Suites
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
    curvePreferences:
      - X25519
      - CurveP521
      - CurveP384
    preferServerCipherSuites: false

database:
  host: localhost
  port: 8080
  tls:
    enabled: false
    verify: false
    cert: ""
    key: ""
    caCertificates: []
    timeout: 60s

# database:
#   driver: mysql
#   host: localhost
#   username: fiber
#   password: password
#   port: 3306
#   database: boilerplate
#   tls: false


session:
  provider: "mysql"
  keyprefix: "session"
  host: "localhost"
  port: 3306
  username: "fiber"
  password: "secret"
  database: "boilerplate"
  tablename: "sessions"
  lookup: "cookie:session_id"

  domain: ""
  samesite: "Lax"
  expiration: "12h"
  secure: false
  gcinterval: "1m"







fiberRequestidEnabled: false
fiberRequestidHeader: "X-Request-ID"
fiberRequestidContextkey: "requestid"
